= Setup JPA 2.1 with TomEE 1

== Preliminary note

TomEE 7 (still in development at the moment) supports JPA 2.1 out of the box. However OpenJPA is still JPA 2.0 for now
so using TomEE 7 you just need to switch the provider to get full JPA 2.1 support. All this sample procedure
is only for TomEE 1.

== Limitations

TomEE 1 only supports JPA 2.0 so JPA descriptors still need to be JPA 2.0 for the container (xsd):

[source]
----
<?xml version="1.0"?>
<persistence version="2.0"
             xmlns="http://java.sun.com/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
                                 http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd">
  <persistence-unit name="demo">
    <jta-data-source>jdbc/demo</jta-data-source>
    <properties>
      <property name="javax.persistence.schema-generation.database.action" value="create"/>
    </properties>
  </persistence-unit>
</persistence>
----

NOTE: however providers will most of the time support JPA 2.1 properties.

== The sample

The sample replace the JPA 2.0 API and the default JPA provider (OpenJPA) by JPA 2.1 API and Hibernate provider through the TomEE Maven Plugin.
This is done using libs feature of the plugin:

[source,xml]
----
<plugin>
  <groupId>org.apache.openejb.maven</groupId>
  <artifactId>tomee-maven-plugin</artifactId>
  <version>1.7.2</version>
  <configuration>
    <context>ROOT</context>
    <simpleLog>true</simpleLog> <!-- nicer for the demo -->
    <libs>
      <!-- use geronimo api jars instead of openejb bundle -->
      <lib>remove:javaee-api</lib>
      <lib>unzip:org.apache.openejb:javaee-api:6.0-6:zip</lib>
      <!-- remove jpa 2.0 api -->
      <lib>remove:geronimo-jpa</lib>
      <!-- add jpa 2.1 api -->
      <lib>org.hibernate.javax.persistence:hibernate-jpa-2.1-api:1.0.0.Final</lib>
      <!-- add hibernate -->
      <lib>org.hibernate:hibernate-entitymanager:4.3.9.Final</lib>
      <lib>org.hibernate:hibernate-core:4.3.9.Final</lib>
      <lib>org.hibernate.common:hibernate-commons-annotations:4.0.5.Final</lib>
      <lib>antlr:antlr:2.7.7</lib>
      <lib>org.jboss:jandex:1.1.0.Final</lib>
      <lib>org.jboss.logging:jboss-logging:3.1.3.GA</lib>
      <lib>org.jboss.logging:jboss-logging-annotations:1.2.0.Beta1</lib>
      <lib>dom4j:dom4j:1.6.1</lib>
      <lib>org.javassist:javassist:3.18.1-GA</lib>
      <!-- optional: remove openjpa -->
      <lib>remove:openjpa</lib>
    </libs>
  </configuration>
</plugin>
----

NOTE: in term of dependencies just ensure JPA 2.1 one is before `javaee-api` one.

If you drop OpenJPA (as done i the sample), don't forget to add in `conf/system.properties` the `javax.persistence.provider` property
to switch back to Hibernate by default.

Running the application (`mvn package tomee:run`) you'll get these logs:

[source]
----
...
INFO - HHH000204: Processing PersistenceUnitInfo [
	name: demo
	...]
INFO - HHH000412: Hibernate Core {4.3.9.Final}
INFO - HHH000206: hibernate.properties not found
INFO - HHH000021: Bytecode provider name : javassist
INFO - HCANN000001: Hibernate Commons Annotations {4.0.5.Final}
INFO - HHH000400: Using dialect: org.hibernate.dialect.HSQLDialect
INFO - HHH000397: Using ASTQueryTranslatorFactory
INFO - HHH000400: Using dialect: org.hibernate.dialect.HSQLDialect
INFO - create table TheMainTable (id bigint generated by default as identity (start with 1), name varchar(255), primary key (id)) --> 1ms
....
INFO - Unwrapped EM = org.hibernate.jpa.internal.EntityManagerImpl@16ba37e3
INFO - Wrapped EM = org.apache.openejb.persistence.JtaEntityManager@7868d54b
...
----

The first part shows hibernate started and the second part shows that you can unwrap the entity manager to use JPA 2.1 specific features:

[source,java]
----
@Lock(READ)
@Singleton
public class MyService {
    @PersistenceContext
    private EntityManager emJpa20;

    @PostConstruct
    private void log() {
        final EntityManager emJpa21 = emJpa20.unwrap(EntityManager.class);
        // ...
    }
}
----

This allows you to use stored procedure API for instance.
